[versions]
android-gradle = "9.0.1"
asm = "9.9.1"

[libraries]
android-gradle-api = { module = "com.android.tools.build:gradle-api", version.ref = "android-gradle" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }